entry-spawn-point:
- ==: org.bukkit.Location
  world: Radlands
  x: -57.40613848109142
  y: 61.0
  z: -33.52230119868431
  pitch: -2.0974958
  yaw: 178.69107
spawn-settings:
  spawn-at-spawnpoint-on-join: true
  spawn-command: true
  respawn-at-spawn: true
  respawn-after-death-at-spawn: false
settings:
  disable_raining: true
  disable-death-msg: true
chat:
  chat_format: '&2[player]&f: [msg]'
  muted: false
  ignored_roles_on_chat-mute:
  - Owner
world: Radlands
x: -58
y: 61
z: -34
pitch: -2.0974958
yaw: 178.69107
