#MariaDB Database
ip = "localhost"
mysql-port = 3306
user = "username"
password = "password"
database = "db_name"

#Velocity - Default settings
motd = "<blue><bold>Mineral <gray><bold>► <red><bold>BotPvP <gray><bold>(1.7-1.20)\n<gray><bold>►<reset> <white><bold>Smartest PvpBots"

#Velocity - Maintenance
maintenance_display = "Maintenance"
maintenance_logo_change = false
maintenance_favicon_Path = "plugins/jeezycore/server-logo-maintenance.png"
motd_maintenance = "<blue><bold>Mineral <gray><bold>- <red><bold>Maintenance\n<gray><bold>►<reset> <white>discord.mineral.gg"
maintenance_kick_message = "Server is in maintenance mode!"

#Velocity - Whitelisted
whitelisted_display = "Whitelisted"
whitelisted_motd = "<blue><bold>Mineral <gray><bold>► <red><bold>BotPvP <gray><bold>(1.7-1.20)\n<gray><bold>►<reset> <white><bold>Smartest PvpBots"
whitelisted_kick_message = "Server is whitelisted!"
whitelisted_access_removed_if_active = "Your whitelist got revoked"
max_players_kick_message = "The server is already full."

#Velocity - JoinMessages
onMaintenance_message = "Server is in maintenance mode!"
onWhitelisted_message = "Server is whitelisted!"