name: JeezyCore
main: de.jeezycore.main.Main
author: JeezyDevelopment
version: 1.0.0
commands:
  create-rank:
    description: Creates rank.
  permissionAdd:
    description: Gives a certain rank permission.
  permissionRemove:
      description: Removes a certain rank permission.
  grant-rank:
    description: Grants selected player a rank.
  chat-disable:
    description: Disables chat.
  chat-enable:
    description: Enables chat.
  jeezy-spawn-set:
    description: Sets entry point when joining.
  spawn:
    description: Teleports you back to spawn.
  ping:
    description: Shows player ping.
  msg:
    description: Message other people.
  r:
    description: Replies to messages.
  day:
    description: Changes player time to day.
  night:
    description: Changes player time to night.
  fly:
    description: Makes you fly.
  core:
      description: Author of the core and version.
  ban:
    description: Bans a player.
  tempban:
    description: Bans a player for a certain time.
  unban:
    description: Unbans a player.
  mute:
    description: Mutes player.
  tempmute:
    description: Mutes a player for a certain time.
  unmute:
    description: Unmutes a player.

