entry-spawn-point:
- ==: org.bukkit.Location
  world: world
  x: 1603.4288399709185
  y: 63.0
  z: 1448.4635743092806
  pitch: 3.6155806
  yaw: 0.3611338
spawn-settings:
  spawn-at-spawnpoint-on-join: true
  spawn-command: true
  respawn-at-spawn: true
  respawn-after-death-at-spawn: false
settings:
  disable_raining: true
  disable-death-msg: true
chat:
  chat_format: "&2[player]&f: [msg]"
  muted: false
  ignored_roles_on_chat-mute:
  - Owner
