name: JeezyCore
main: de.jeezycore.main.Main
author: JeezyDevelopment
version: 1.0.0
commands:
  jeezycore-guide:
    description: Helps you to navigate through the plugin.
  create-rank:
    description: Creates rank.
  grant-rank:
    description: Grants selected player a rank.
  chat-disable:
    description: Disables chat.
  chat-enable:
    description: Enables chat.
  jeezy-spawn-set:
    description: Sets entry point when joining.
  ping:
    description: Shows player ping.
  msg:
    description: Message other people.
